// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Song$ReactTemplate = require("./Song.bs.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, Song$ReactTemplate.Demo[/* make */2](/* array */[])), "body");

/*  Not a pure module */
