// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Top$ReactTemplate = require("./Top.bs.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, Top$ReactTemplate.make(/* :: */[
              0,
              /* :: */[
                5,
                /* :: */[
                  25,
                  /* [] */0
                ]
              ]
            ], /* array */[])), "body");

/*  Not a pure module */
